### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by piripera** [atolcd/alfresco-event-scheduling#11]
Hi
i'm trying to install your add-on on my Alfresco community test, but the mvn install find a problem.

[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Alfresco Platform/Repository JAR Module 1.0.7
[INFO] ------------------------------------------------------------------------
Downloading: https://artifacts.alfresco.com/nexus/content/groups/private/org/alfresco/maven/alfresco-rad/3.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.alfresco.maven:alfresco-rad:3.0.0-SNAPSHOT/maven-metadata.xml from/to alfresco-private-repository (https://artifacts.alfresco.com/nexus/content/groups/private): Not authorized , ReasonPhrase:Unauthorized.
[WARNING] Failure to transfer org.alfresco.maven:alfresco-rad:3.0.0-SNAPSHOT/maven-metadata.xml from https://artifacts.alfresco.com/nexus/content/groups/private was cached in the local repository, resolution will not be reattempted until the update interval of alfresco-private-repository has elapsed or updates are forced. Original error: Could not transfer metadata org.alfresco.maven:alfresco-rad:3.0.0-SNAPSHOT/maven-metadata.xml from/to alfresco-private-repository (https://artifacts.alfresco.com/nexus/content/groups/private): Not authorized , ReasonPhrase:Unauthorized.
Downloading: https://artifacts.alfresco.com/nexus/content/groups/private/org/alfresco/maven/alfresco-rad/3.0.0-SNAPSHOT/alfresco-rad-3.0.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Alfresco Event Scheduling .......................... SUCCESS [  0.855 s]
[INFO] Alfresco Platform/Repository JAR Module ............ FAILURE [  2.050 s]
[INFO] Alfresco Share JAR Module .......................... SKIPPED
[INFO] Integration Tests Module ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.349 s
[INFO] Finished at: 2017-10-10T08:31:44+02:00
[INFO] Final Memory: 21M/208M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project alfresco-event-scheduling-platform-jar: Could not resolve dependencies for project com.atolcd:alfresco-event-scheduling-platform-jar:jar:1.0.7: Failed to collect dependencies at org.alfresco.maven:alfresco-rad:jar:3.0.0-SNAPSHOT: Failed to read artifact descriptor for org.alfresco.maven:alfresco-rad:jar:3.0.0-SNAPSHOT: Could not transfer artifact org.alfresco.maven:alfresco-rad:pom:3.0.0-SNAPSHOT from/to alfresco-private-repository (https://artifacts.alfresco.com/nexus/content/groups/private): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]
[ERROR]

It seams that it look a component on a professional section

Can you help me, please?

Regards
Fabrizio

**Comment by bforest** [comment]
Hi,

I see that the pom.xml contains an URL reserved to enterprise customers: https://artifacts.alfresco.com/nexus/content/groups/private

I think , you have two choices :

Replace https://artifacts.alfresco.com/nexus/content/groups/private by https://artifacts.alfresco.com/nexus/content/groups/public
Or comment         
Regards.

**Comment by piripera** [comment]
Good morning 
i tried every change but I have the same problem. It need alfresco-rad. Is it possible I have to comment something else?

With comment

[ERROR] Failed to execute goal on project alfresco-event-scheduling-platform-jar: Could not resolve dependencies for project com.atolcd:alfresco-event-scheduling-platform-jar:jar:1.0.7: Failure to find org.alfresco.maven:alfresco-rad:jar:3.0.0-SNAPSHOT in https://artifacts.alfresco.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of alfresco-public has elapsed or updates are forced -> [Help 1]

With replace

[INFO] ------------------------------------------------------------------------
[INFO] Building Alfresco Platform/Repository JAR Module 1.0.7
[INFO] ------------------------------------------------------------------------
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/maven/alfresco-rad/3.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] The POM for org.alfresco.maven:alfresco-rad:jar:3.0.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Alfresco Event Scheduling .......................... SUCCESS [  0.606 s]
[INFO] Alfresco Platform/Repository JAR Module ............ FAILURE [  1.980 s]
[INFO] Alfresco Share JAR Module .......................... SKIPPED
[INFO] Integration Tests Module ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.897 s
[INFO] Finished at: 2017-10-10T17:13:54+02:00
[INFO] Final Memory: 22M/226M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project alfresco-event-scheduling-platform-jar: Could not resolve dependencies for project com.atolcd:alfresco-event-scheduling-platform-jar:jar:1.0.7: Failure to find org.alfresco.maven:alfresco-rad:jar:3.0.0-SNAPSHOT in https://artifacts.alfresco.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of alfresco-public has elapsed or updates are forced -> [Help 1]

thanks a lot for your support
Fabrizio

**Comment by sprouvez** [comment]
Hello,

If you change the alfresco sdk version for the 3.0.1 (release) version and you comment the part of repository "enterprise" (alfresco-private-repository) you could build the jar.

Regards.
Stephane

**Comment by piripera** [comment]
Thanks, but it doesn't works

[WARNING] The POM for org.alfresco.maven:alfresco-rad:jar:3.0.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Alfresco Event Scheduling .......................... SUCCESS [  1.019 s]
[INFO] Alfresco Platform/Repository JAR Module ............ FAILURE [  0.601 s]
[INFO] Alfresco Share JAR Module .......................... SKIPPED
[INFO] Integration Tests Module ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.212 s
[INFO] Finished at: 2017-10-10T18:41:11+02:00
[INFO] Final Memory: 20M/174M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project alfresco-event-scheduling-platform-jar: Could not resolve dependencies for project com.atolcd:alfresco-event-scheduling-platform-jar:jar:1.0.7: Failure to find org.alfresco.maven:alfresco-rad:jar:3.0.1-SNAPSHOT in https://artifacts.alfresco.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of alfresco-public has elapsed or updates are forced -> [Help 1]
[ERROR]

**Comment by sprouvez** [comment]
Hello Fabrizio

Do you have some customs in your settings.xml of your maven home directory ? Maybe the problem is here.

Stephane

**Comment by piripera** [comment]
Hi Stefane
I have installed a clean maven via apt.without customs. I use the last alfresco community version
I'm sorry for the trouble, but I would like really to try your add-on
Thanks

root@DoCS:/etc/maven# mvn -version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_141, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: it_IT, platform encoding: UTF-8
OS name: "linux", version: "4.9.0-3-amd64", arch: "amd64", family: "unix"
root@DoCS:/etc/maven#

root@DoCS:/etc/maven# cat m2.conf
main is org.apache.maven.cli.MavenCli from plexus.core

set maven.home default ${user.home}/m2

[plexus.core]
optionally ${maven.home}/lib/ext/*.jar
load       ${maven.home}/lib/*.jar
load       ${maven.home}/conf/logging
root@DoCS:/etc/maven#


root@DoCS:/etc/maven# cat settings.xml
<?xml version="1.0" encoding="UTF-8"?>




<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  

  

  

  
  <pluginGroups>
    
  </pluginGroups>

  
  <proxies>
    
  </proxies>

  
  <servers>
    

    
  </servers>

  
  <mirrors>
    
  </mirrors>

  
  <profiles>
    

    
  </profiles>

  
</settings>
root@DoCS:/etc/maven#



root@DoCS:/etc/maven# cat toolchains.xml
<?xml version="1.0" encoding="UTF-8"?>




<toolchains xmlns="http://maven.apache.org/TOOLCHAINS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/TOOLCHAINS/1.1.0 http://maven.apache.org/xsd/toolchains-1.1.0.xsd">

  

</toolchains>root@DoCS:/etc/maven#

**Comment by piripera** [comment]
root@DoCS:/etc/maven# cat settings.xml
<?xml version="1.0" encoding="UTF-8"?>




<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  

  

  

  
  <pluginGroups>
    
  </pluginGroups>

  
  <proxies>
    
  </proxies>

  
  <servers>
    

    
  </servers>

  
  <mirrors>
    
  </mirrors>

  
  <profiles>
    

    
  </profiles>

  
</settings>

**Comment by piripera** [comment]
root@DoCS:/etc/maven# cat settings.xml
<?xml version="1.0" encoding="UTF-8"?>




<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">

**Comment by piripera** [comment]
Let me know if you need the setting file.
I cannot copy the contents of the file settings.xml with success.

**Comment by sprouvez** [comment]
Hello Fabrizio,

I don't know why the compilation failed. But you can find in attatchment the zip file that contains all amps.

Regards
Stephane

[alfresco-event-scheduling.zip](https://github.com/atolcd/alfresco-event-scheduling/files/1378373/alfresco-event-scheduling.zip)

**Comment by piripera** [comment]
ohhhhh, thanks a lot Stefane. Now I could install your add-on.
It is very nice and well done. But.... I find the same problem detected on 2015 by someone else
Is it possible??


**2017-10-12 22:08:20,595  ERROR [freemarker.runtime] [http-apr-8080-exec-3] Error executing FreeMarker template
 FreeMarker template error:
The following has evaluated to null or missing:
==> eventSchedulingUtils  [in template "workspace://SpacesStore/071eeb69-10c6-4065-ac17-2198a9c7afec" at line 49, column 208]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction (FTL stack trace):
----------
==> ${eventSchedulingUtils.getPersonFullN...  [in template "workspace://SpacesStore/071eeb69-10c6-4065-ac17-2198a9c7afec" at line 49, column 206]
----------**

Java stack trace (for programmers):
----------
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
        at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:98)
        at freemarker.core.UnexpectedTypeException.newDesciptionBuilder(UnexpectedTypeException.java:41)
        at freemarker.core.UnexpectedTypeException.<init>(UnexpectedTypeException.java:24)
        at freemarker.core.Dot._eval(Dot.java:81)
        at freemarker.core.Expression.eval(Expression.java:111)
        at freemarker.core.MethodCall._eval(MethodCall.java:91)
        at freemarker.core.Expression.eval(Expression.java:111)
        at freemarker.core.Expression.evalAndCoerceToString(Expression.java:115)
        at freemarker.core.StringBuiltins$StringBuiltIn._eval(StringBuiltins.java:87)
        at freemarker.core.Expression.eval(Expression.java:111)
        at freemarker.core.Expression.evalAndCoerceToString(Expression.java:115)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:76)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.Environment.process(Environment.java:243)
        at org.alfresco.repo.template.FreeMarkerProcessor.process(FreeMarkerProcessor.java:230)
        at org.alfresco.repo.processor.TemplateServiceImpl.processTemplate(TemplateServiceImpl.java:184)
        at org.alfresco.repo.processor.TemplateServiceImpl.processTemplate(TemplateServiceImpl.java:247)
        at org.alfresco.repo.action.executer.MailActionExecuter$3.prepare(MailActionExecuter.java:965)
        at org.alfresco.repo.action.executer.MailActionExecuter.prepareEmail(MailActionExecuter.java:1026)
        at org.alfresco.repo.action.executer.MailActionExecuter.prepareEmails(MailActionExecuter.java:585)
        at org.alfresco.repo.action.executer.MailActionExecuter.executeImpl(MailActionExecuter.java:490)
        at org.alfresco.repo.action.executer.ActionExecuterAbstractBase.execute(ActionExecuterAbstractBase.java:273)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.alfresco.repo.management.subsystems.SubsystemProxyFactory$1.invoke(SubsystemProxyFactory.java:79)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy307.execute(Unknown Source)
        at org.alfresco.repo.action.ActionServiceImpl.directActionExecution(ActionServiceImpl.java:856)
        at org.alfresco.repo.action.ActionServiceImpl.executeActionImpl(ActionServiceImpl.java:757)
        at org.alfresco.repo.action.ActionServiceImpl.executeAction(ActionServiceImpl.java:581)
        at org.alfresco.repo.action.ActionServiceImpl.executeAction(ActionServiceImpl.java:567)
        at org.alfresco.repo.action.ActionServiceImpl.executeAction(ActionServiceImpl.java:865)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.alfresco.repo.security.permissions.impl.AlwaysProceedMethodInterceptor.invoke(AlwaysProceedMethodInterceptor.java:41)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:53)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.alfresco.repo.audit.AuditMethodInterceptor.invoke(AuditMethodInterceptor.java:166)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy47.executeAction(Unknown Source)
        at org.alfresco.repo.jscript.ScriptAction.executeImpl(ScriptAction.java:173)
        at org.alfresco.repo.jscript.ScriptAction.execute(ScriptAction.java:143)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
        at org.mozilla.javascript.gen.classpath__alfresco_extension_templates_webscripts_com_atolcd_slingshot_dashlets_event_scheduling_notify_user_post_js_18._c_notifyUser_10(classpath*:alfresco/extension/templates/webscripts/com/atolcd/slingshot/dashlets/event-scheduling/notify-user.post.js:170)
        at org.mozilla.javascript.gen.classpath__alfresco_extension_templates_webscripts_com_atolcd_slingshot_dashlets_event_scheduling_notify_user_post_js_18.call(classpath*:alfresco/extension/templates/webscripts/com/atolcd/slingshot/dashlets/event-scheduling/notify-user.post.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
        at org.mozilla.javascript.gen.classpath__alfresco_extension_templates_webscripts_com_atolcd_slingshot_dashlets_event_scheduling_notify_user_post_js_18._c_notifyAllUsers_11(classpath*:alfresco/extension/templates/webscripts/com/atolcd/slingshot/dashlets/event-scheduling/notify-user.post.js:190)
        at org.mozilla.javascript.gen.classpath__alfresco_extension_templates_webscripts_com_atolcd_slingshot_dashlets_event_scheduling_notify_user_post_js_18.call(classpath*:alfresco/extension/templates/webscripts/com/atolcd/slingshot/dashlets/event-scheduling/notify-user.post.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
        at org.mozilla.javascript.gen.classpath__alfresco_extension_templates_webscripts_com_atolcd_slingshot_dashlets_event_scheduling_notify_user_post_js_18._c_main_19(classpath*:alfresco/extension/templates/webscripts/com/atolcd/slingshot/dashlets/event-scheduling/notify-user.post.js:436)
        at org.mozilla.javascript.gen.classpath__alfresco_extension_templates_webscripts_com_atolcd_slingshot_dashlets_event_scheduling_notify_user_post_js_18.call(classpath*:alfresco/extension/templates/webscripts/com/atolcd/slingshot/dashlets/event-scheduling/notify-user.post.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74)
        at org.mozilla.javascript.gen.classpath__alfresco_extension_templates_webscripts_com_atolcd_slingshot_dashlets_event_scheduling_notify_user_post_js_18._c_script_0(classpath*:alfresco/extension/templates/webscripts/com/atolcd/slingshot/dashlets/event-scheduling/notify-user.post.js:457)
        at org.mozilla.javascript.gen.classpath__alfresco_extension_templates_webscripts_com_atolcd_slingshot_dashlets_event_scheduling_notify_user_post_js_18.call(classpath*:alfresco/extension/templates/webscripts/com/atolcd/slingshot/dashlets/event-scheduling/notify-user.post.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
        at org.mozilla.javascript.gen.classpath__alfresco_extension_templates_webscripts_com_atolcd_slingshot_dashlets_event_scheduling_notify_user_post_js_18.call(classpath*:alfresco/extension/templates/webscripts/com/atolcd/slingshot/dashlets/event-scheduling/notify-user.post.js)
        at org.mozilla.javascript.gen.classpath__alfresco_extension_templates_webscripts_com_atolcd_slingshot_dashlets_event_scheduling_notify_user_post_js_18.exec(classpath*:alfresco/extension/templates/webscripts/com/atolcd/slingshot/dashlets/event-scheduling/notify-user.post.js)
        at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:509)
        at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:207)
        at org.alfresco.repo.processor.ScriptServiceImpl.execute(ScriptServiceImpl.java:219)
        at org.alfresco.repo.processor.ScriptServiceImpl.executeScript(ScriptServiceImpl.java:181)
        at org.alfresco.repo.web.scripts.RepositoryScriptProcessor.executeScript(RepositoryScriptProcessor.java:109)
        at org.springframework.extensions.webscripts.AbstractWebScript.executeScript(AbstractWebScript.java:1376)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:86)
        at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:519)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:587)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:656)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:428)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:308)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:399)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)
        at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2486)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
2017-10-12 22:08:20,610  ERROR [util.transaction.TransactionSupportUtil] [http-apr-8080-exec-3] After completion (committed) TransactionalCache exception
 java.lang.NullPointerException
        at org.alfresco.repo.action.executer.MailActionExecuter.sendEmail(MailActionExecuter.java:1048)
        at org.alfresco.repo.action.executer.MailActionExecuter.access$4(MailActionExecuter.java:1040)
        at org.alfresco.repo.action.executer.MailActionExecuter$2$1.execute(MailActionExecuter.java:510)
        at org.alfresco.repo.action.executer.MailActionExecuter$2$1.execute(MailActionExecuter.java:1)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464)
        at org.alfresco.repo.action.executer.MailActionExecuter$2.afterCommit(MailActionExecuter.java:504)
        at org.alfresco.util.transaction.TransactionSupportUtil$TransactionSynchronizationImpl.afterCompletion(TransactionSupportUtil.java:597)
        at org.springframework.transaction.support.TransactionSynchronizationUtils.invokeAfterCompletion(TransactionSynchronizationUtils.java:168)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.invokeAfterCompletion(AbstractPlatformTransactionManager.java:994)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.triggerAfterCompletion(AbstractPlatformTransactionManager.java:969)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:800)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:724)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:475)
        at org.alfresco.util.transaction.SpringAwareUserTransaction.commit(SpringAwareUserTransaction.java:482)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:486)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:587)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:656)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:428)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:308)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:399)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)
        at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2486)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by piripera** [comment]
Hello, 
I'm sorry to ask again, but let me know if there is a solution to send email notification or it is too hard with the new alfresco version.
Thanks a lot 
Fabrizio
